<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8HoUjd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8HoUjd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR8HoUjd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR8HoUjd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR8HoUjd\App_KernelDevDebugContainer([
    'container.build_hash' => 'R8HoUjd',
    'container.build_id' => '2f3804a5',
    'container.build_time' => 1647365305,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR8HoUjd');
