<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNHi1kET\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNHi1kET/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNHi1kET.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNHi1kET\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNHi1kET\App_KernelDevDebugContainer([
    'container.build_hash' => 'NHi1kET',
    'container.build_id' => '54b286e0',
    'container.build_time' => 1647377196,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNHi1kET');
